<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $addons = [
            ['slug' => 'store-launch', 'category' => 'technology', 'name_ar' => 'إطلاق متجر احترافي', 'name_en' => 'Professional store launch', 'subtitle_ar' => 'Salla أو Zid أو Shopify مع تجهيز رحلة الشراء', 'subtitle_en' => 'Salla, Zid, or Shopify with a conversion-ready buying journey', 'price_sar' => 1800, 'billing_cycle' => 'one_time', 'tag_ar' => 'متاجر', 'tag_en' => 'Stores', 'features_ar' => ['تجهيز المتجر', 'تحسين رحلة الشراء'], 'features_en' => ['Store setup', 'Buying journey optimization'], 'sort_order' => 1],
            ['slug' => 'market-pos', 'category' => 'technology', 'name_ar' => 'نظام Market POS', 'name_en' => 'Market POS system', 'subtitle_ar' => 'نقاط بيع ومخزون وتشغيل يومي أكثر وضوحاً', 'subtitle_en' => 'Clearer point-of-sale, inventory, and daily operations', 'price_sar' => 2500, 'billing_cycle' => 'one_time', 'tag_ar' => 'أنظمة', 'tag_en' => 'Systems', 'features_ar' => ['نقاط البيع', 'إدارة المخزون'], 'features_en' => ['Point of sale', 'Inventory management'], 'sort_order' => 2],
            ['slug' => 'liftdesk-automation', 'category' => 'technology', 'name_ar' => 'أتمتة LiftDesk بالذكاء الاصطناعي', 'name_en' => 'LiftDesk AI automation', 'subtitle_ar' => 'تحويل الرسائل والتقارير إلى مهام وتنبيهات منظمة', 'subtitle_en' => 'Turn messages and reports into organized tasks and alerts', 'price_sar' => 750, 'billing_cycle' => 'monthly', 'tag_ar' => 'أتمتة', 'tag_en' => 'Automation', 'features_ar' => ['تحويل الرسائل إلى مهام', 'تنبيهات متابعة'], 'features_en' => ['Turn messages into tasks', 'Follow-up alerts'], 'sort_order' => 3],
            ['slug' => 'custom-system', 'category' => 'technology', 'name_ar' => 'نظام مخصص لمشروعك', 'name_en' => 'Custom system for your business', 'subtitle_ar' => 'نطاق مخصص للوحة تحكم أو SaaS أو نظام عمليات', 'subtitle_en' => 'A tailored scope for a dashboard, SaaS, or operations system', 'price_sar' => 4500, 'billing_cycle' => 'one_time', 'tag_ar' => 'تطوير', 'tag_en' => 'Development', 'features_ar' => ['نطاق مخصص', 'لوحة تشغيل أو SaaS'], 'features_en' => ['Tailored scope', 'Operating dashboard or SaaS'], 'sort_order' => 4],
            ['slug' => 'tracking-dashboard', 'category' => 'technology', 'name_ar' => 'لوحة قياس الأداء', 'name_en' => 'Performance dashboard', 'subtitle_ar' => 'ربط المؤشرات الأساسية في لوحة واحدة مفهومة', 'subtitle_en' => 'Bring the core signals into one clear operating view', 'price_sar' => 600, 'billing_cycle' => 'one_time', 'tag_ar' => 'بيانات', 'tag_en' => 'Data', 'features_ar' => ['مؤشرات واضحة', 'قراءة شهرية'], 'features_en' => ['Clear metrics', 'Monthly readout'], 'sort_order' => 5],
        ];

        foreach ($addons as $addon) {
            DB::table('package_addons')->updateOrInsert(
                ['slug' => $addon['slug']],
                array_merge($addon, [
                    'features_ar' => json_encode($addon['features_ar'], JSON_UNESCAPED_UNICODE),
                    'features_en' => json_encode($addon['features_en'], JSON_UNESCAPED_UNICODE),
                    'is_featured' => false,
                    'is_published' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }

        $projects = [
            ['slug' => 'al-owaid', 'name_ar' => 'براند العويد للعود', 'name_en' => 'Al Owaid Oud', 'category_ar' => 'تسويق الأداء', 'category_en' => 'Performance Marketing', 'description_ar' => 'استراتيجية استحواذ لبراند عطور فاخر على منصة سلة، مع تحسين رحلة الشراء وإعادة الاستهداف.', 'description_en' => 'An acquisition strategy for a premium fragrance brand on Salla, with a sharper purchase journey and retargeting system.', 'challenge_ar' => 'كان المطلوب رفع كفاءة الاستحواذ وتحويل الاهتمام بالمنتج إلى عمليات شراء قابلة للقياس.', 'challenge_en' => 'The brief was to improve acquisition efficiency and turn product interest into measurable purchases.', 'strategy_ar' => 'إعادة بناء الرسائل الإبداعية ومسار الشراء، ثم تحسين الحملات بناءً على إشارات السلة والدفع والشراء.', 'strategy_en' => 'We refined the creative message and purchase path, then optimized campaigns around cart, checkout, and purchase signals.', 'metric_ar' => '2.62x ROAS', 'metric_en' => '2.62x ROAS', 'outcome_ar' => 'عائد شراء مثبت', 'outcome_en' => 'Verified purchase return', 'results' => ['عائد شراء 2.62x', '1,137 عملية شراء', '8,274 إضافة إلى السلة', 'إنفاق إعلاني $28,268.79'], 'period_en' => 'Nov 1–29, 2025', 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل، والفترة موضحة حيث ظهرت في المصدر.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots; the period is shown where visible in the source.', 'image_url' => 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=600&auto=format&fit=crop', 'sort_order' => 1],
            ['slug' => 'barner', 'name_ar' => 'براند بارنر', 'name_en' => 'Barner Brand', 'category_ar' => 'استحواذ وتحسين ميتا', 'category_en' => 'Acquisition & Meta Optimization', 'description_ar' => 'تحسين حملات الاستحواذ من خلال اختبار الإعلانات والجماهير وربط كل مرحلة من القمع بالشراء.', 'description_en' => 'Acquisition optimization built around creative and audience testing, with each funnel stage tied back to purchase.', 'challenge_ar' => 'الحاجة إلى تقليل الهدر الإعلاني وتحويل الإضافات إلى السلة والدفع إلى عمليات شراء أكثر كفاءة.', 'challenge_en' => 'The challenge was to reduce wasted spend and convert cart and checkout intent into more efficient purchases.', 'strategy_ar' => 'تحليل حملات ميتا، إعادة توزيع الإنفاق، وتحسين الإعلانات والجماهير وفقاً لإشارات القمع الفعلية.', 'strategy_en' => 'We analyzed Meta campaigns, reallocated spend, and improved creative and audiences using real funnel signals.', 'metric_ar' => '2.10x ROAS', 'metric_en' => '2.10x ROAS', 'outcome_ar' => '40 عملية شراء', 'outcome_en' => '40 purchases', 'results' => ['متوسط عائد شراء 2.10x', '40 عملية شراء', '146 إضافة إلى السلة', 'قيمة شراء $3,223.72'], 'period_en' => 'Oct 1–31, 2025', 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل، والفترة موضحة حيث ظهرت في المصدر.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots; the period is shown where visible in the source.', 'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop', 'sort_order' => 2],
            ['slug' => 'toyo', 'name_ar' => 'تطبيق تويو', 'name_en' => 'Toyo App', 'category_ar' => 'هندسة النمو', 'category_en' => 'Growth Engineering', 'description_ar' => 'نمو تجاري لخدمة توصيل مع التركيز على الطلبات، قيمة السلة، وتحسين قابلية التوسع.', 'description_en' => 'Commercial growth for a delivery service focused on orders, basket value, and scalable performance.', 'challenge_ar' => 'الحاجة إلى زيادة المبيعات والطلبات مع الحفاظ على كفاءة التشغيل في فترة مقارنة واضحة.', 'challenge_en' => 'The business needed more sales and orders while maintaining operational efficiency across a comparable period.', 'strategy_ar' => 'تحسين الاستحواذ والعروض وقراءة مؤشرات المبيعات والطلبات والمنتجات المباعة لاتخاذ قرارات توسع أفضل.', 'strategy_en' => 'We improved acquisition and offers while using sales, orders, and product data to guide better scaling decisions.', 'metric_ar' => 'KWD 2,567.558', 'metric_en' => 'KWD 2,567.558', 'outcome_ar' => 'إجمالي المبيعات', 'outcome_en' => 'Total sales', 'results' => ['إجمالي مبيعات KWD 2,567.558', '130 طلباً', '251 منتجاً مباعاً', 'متوسط قيمة الطلب KWD 19.320'], 'period_en' => 'Mar 1–31, 2025', 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots.', 'image_url' => 'https://images.unsplash.com/photo-1526367790999-0150786486a9?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1526367790999-0150786486a9?q=80&w=600&auto=format&fit=crop', 'sort_order' => 3],
            ['slug' => 'qanatir', 'name_ar' => 'براند قناطير الغذائي', 'name_en' => 'Qanatir Food Brand', 'category_ar' => 'الإعلانات المدفوعة', 'category_en' => 'Paid Social', 'description_ar' => 'توسيع التجارة الإلكترونية عبر محتوى أداء وحملات مدفوعة تربط الإنفاق بالشراء الفعلي.', 'description_en' => 'E-commerce growth through performance creative and paid campaigns tied to actual purchase outcomes.', 'challenge_ar' => 'تحويل الاهتمام بالمنتج الغذائي إلى عمليات شراء قابلة للقياس بميزانية اختبار منضبطة.', 'challenge_en' => 'The challenge was to turn food-product interest into measurable purchases with disciplined test spend.', 'strategy_ar' => 'اختبار الإبداع والجمهور وتحسين الحملات وفقاً لمراحل الدفع والشراء، لا وفقاً للتفاعل السطحي فقط.', 'strategy_en' => 'We tested creative and audiences, optimizing against checkout and purchase stages rather than surface engagement alone.', 'metric_ar' => '2.54x ROAS', 'metric_en' => '2.54x ROAS', 'outcome_ar' => '22 عملية شراء', 'outcome_en' => '22 purchases', 'results' => ['عائد شراء 2.54x', '22 عملية شراء', 'قيمة شراء $1,249.74', '175 بدءاً للدفع'], 'period_en' => 'Aug 1–31, 2025', 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots.', 'image_url' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=600&auto=format&fit=crop', 'sort_order' => 4],
            ['slug' => 'jassar', 'name_ar' => 'مؤسسة جسار التجارية', 'name_en' => 'Jassar Trading', 'category_ar' => 'تحسين رحلة التحويل', 'category_en' => 'Conversion Journey', 'description_ar' => 'تحسين مسار التجارة وتحويل الزيارات إلى طلبات وعملاء ضمن تجربة قياس واضحة.', 'description_en' => 'A commerce journey optimized to turn visits into orders and customers through clearer measurement.', 'challenge_ar' => 'الحاجة إلى فهم القمع التجاري بالكامل من الزيارات وحتى الطلبات والعملاء.', 'challenge_en' => 'The business needed visibility across the full commerce funnel, from visits to orders and customers.', 'strategy_ar' => 'قراءة مسار الزيارة والمنتج والسلة والطلب، مع تحسين نقاط التسرب في تجربة الشراء.', 'strategy_en' => 'We mapped the visit, product, cart, and order journey, then improved the main drop-off points in the buying experience.', 'metric_ar' => '3,228 طلباً', 'metric_en' => '3,228 orders', 'outcome_ar' => 'نمو التجارة', 'outcome_en' => 'Commerce growth', 'results' => ['3,228 طلباً', '137,893 زيارة', '3,177 عميلاً', 'إجمالي مبيعات 626,170.85'], 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots.', 'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop', 'sort_order' => 5],
            ['slug' => 'flash', 'name_ar' => 'براند فلاش', 'name_en' => 'Flash Brand', 'category_ar' => 'نمو متعدد القنوات', 'category_en' => 'Omnichannel Growth', 'description_ar' => 'تحسين الأداء المدفوع عبر حملات مرتبطة بقيمة الشراء ونقاط بدء الدفع.', 'description_en' => 'Paid performance optimization tied to purchase value and checkout-start signals.', 'challenge_ar' => 'رفع كفاءة الإنفاق وتحسين نسبة الانتقال من بدء الدفع إلى الشراء.', 'challenge_en' => 'The goal was to improve spend efficiency and strengthen the path from checkout start to purchase.', 'strategy_ar' => 'تطوير الإعلانات والجماهير وتحسين الحملات بناءً على قيمة الشراء والتكلفة لكل بدء دفع.', 'strategy_en' => 'We improved creative and audiences using purchase value and cost-per-checkout signals.', 'metric_ar' => '2.34x ROAS', 'metric_en' => '2.34x ROAS', 'outcome_ar' => '242 عملية شراء', 'outcome_en' => '242 purchases', 'results' => ['عائد شراء 2.34x', '242 عملية شراء', 'قيمة شراء $15,260.71', '524 بدءاً للدفع'], 'period_en' => 'May 1–31, 2025', 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots.', 'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop', 'sort_order' => 6],
            ['slug' => 'kamalz', 'name_ar' => 'براند كاملز', 'name_en' => 'Kamalz Brand', 'category_ar' => 'تحسين الاستحواذ', 'category_en' => 'Acquisition Optimization', 'description_ar' => 'حملة أداء بإنفاق مضبوط لتحويل الزيارات وبدء الدفع إلى مشتريات قابلة للقياس.', 'description_en' => 'A disciplined performance campaign converting traffic and checkout intent into measurable purchases.', 'challenge_ar' => 'الحاجة إلى اختبار كفاءة الإنفاق وتحسين المراحل السابقة للشراء دون توسيع الميزانية بلا دليل.', 'challenge_en' => 'The brief was to test spend efficiency and improve pre-purchase stages before scaling the budget.', 'strategy_ar' => 'متابعة تكلفة بدء الدفع وقيمة الشراء والعائد، ثم تحسين توزيع الإنفاق على الإعلانات الأفضل.', 'strategy_en' => 'We tracked checkout cost, purchase value, and return, then shifted spend toward the strongest ads.', 'metric_ar' => '1.89x ROAS', 'metric_en' => '1.89x ROAS', 'outcome_ar' => '39 عملية شراء', 'outcome_en' => '39 purchases', 'results' => ['عائد شراء 1.89x', '39 عملية شراء', 'قيمة شراء $2,823.10', '173 بدءاً للدفع'], 'period_en' => 'Aug 1–31, 2025', 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots.', 'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop', 'sort_order' => 7],
            ['slug' => 'manabet', 'name_ar' => 'منابت', 'name_en' => 'Manabet', 'category_ar' => 'نمو التجارة الإلكترونية', 'category_en' => 'E-commerce Growth', 'description_ar' => 'تحسين أداء المتجر عبر متابعة المبيعات والطلبات والزيارات والعملاء في لوحة تشغيل واحدة.', 'description_en' => 'Store performance tracked through a single operating view for sales, orders, visits, and customers.', 'challenge_ar' => 'الحاجة إلى رؤية أبسط لما يحدث داخل المتجر من الزيارة إلى الطلب والعميل.', 'challenge_en' => 'The business needed a clearer view of what happens inside the store from visit to order and customer.', 'strategy_ar' => 'ربط مؤشرات المتجر الأساسية في قراءة واحدة تساعد على اتخاذ قرارات نمو أسرع.', 'strategy_en' => 'We brought the core store signals into one view to support faster growth decisions.', 'metric_ar' => 'KWD 753.76', 'metric_en' => 'KWD 753.76', 'outcome_ar' => 'إجمالي المبيعات', 'outcome_en' => 'Total sales', 'results' => ['إجمالي مبيعات KWD 753.76', '66 طلباً', '2,340 زيارة', '60 عميلاً'], 'evidence_note_ar' => 'الأرقام المعروضة مأخوذة من لقطات لوحات الأداء المقدمة من العميل.', 'evidence_note_en' => 'The figures are taken from the supplied performance-dashboard screenshots.', 'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', 'thumbnail_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop', 'sort_order' => 8],
        ];

        foreach ($projects as $project) {
            DB::table('portfolio_projects')->updateOrInsert(
                ['slug' => $project['slug']],
                array_merge($project, [
                    'results' => json_encode($project['results'], JSON_UNESCAPED_UNICODE),
                    'gallery' => json_encode([], JSON_UNESCAPED_UNICODE),
                    'metadata' => json_encode(['source' => 'legacy-static-evidence'], JSON_UNESCAPED_UNICODE),
                    'is_published' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }

    public function down(): void
    {
        // This migration is intentionally non-destructive: its records are editable CMS content.
    }
};
